### ISSUE TITLE
Installing the dependencies failed: Module 'Serge' is not installed

### ISSUE THREAD

**Issue by icnocop** [dragosv/serge-plugins#4] opened 2018-10-31 20:35 UTC
Hi.

Thank you for serge plugins.

I installed Serge 1.3 as indicated in https://serge.io/download/?win/stable.

I then tried to install the zanata serge plugin using the following command:

`cpanm install Serge::Sync::Plugin::TranslationService::zanata`

But I got the following error:
```
--> Working on install
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/install-0.01.tar.gz ... OK
Configuring install-0.01 ... OK
Building and testing install-0.01 ... OK
Successfully installed install-0.01
--> Working on Serge::Sync::Plugin::TranslationService::zanata
Fetching http://www.cpan.org/authors/id/D/DR/DRAGOSV/Serge-Sync-Plugin-TranslationService-zanata-0.903.0.tar.gz ... OK
Configuring Serge-Sync-Plugin-TranslationService-zanata-0.903.0 ... OK
==> Found dependencies: Serge
--> Working on Serge
Fetching http://www.cpan.org/authors/id/A/AF/AFAN/Serge-v1.3.2.tar.gz ... OK
Configuring Serge-v1.3.2 ... OK
Building and testing Serge-v1.3.2 ... FAIL
! Installing Serge failed. See C:\Users\ADMINI~1\.cpanm\work\1541017770.4628\build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Serge' is not installed
! Bailing out the installation for Serge-Sync-Plugin-TranslationService-zanata-0.903.0.
1 distribution installed
```

[build.log](https://github.com/dragosv/serge-plugins/files/2536300/build.log)

Any ideas?

Is the zanata plugin not compatible with the installation instructions in https://serge.io/download/?win/stable?

Thank you.

**Comment by iafan** [comment] 2018-10-31 21:09
@icnocop, this is Serge guy speaking. I see there's one test failing, and I wonder if this is some Windows-specific issue:
```
Failed test 'Directory 'test-output\errors' exists but 'reference-output\errors' doesn't'
    #   at C:\Users\ADMINI~1\.cpanm\work\1541017770.4628\Serge-v1.3.2\t\lib/Test/Diff.pm line 58.

        #   Failed test 'File 'C:\Users\ADMINI~1\.cpanm\work\1541017770.4628\Serge-v1.3.2\t\data\engine\issues\5\reference-output\errors\test_job.txt' should exist'
        #   at C:\Users\ADMINI~1\.cpanm\work\1541017770.4628\Serge-v1.3.2\t\lib/Test/Diff.pm line 42.
```

Can you try installing the latest version separately first? https://serge.io/download/?win/latest once you have Serge installed, run `t/engine.t` and see if it produces the same error. If it does, please create an issue at https://github.com/evernote/serge/issues since this seems to be strictly Serge-related?

**Comment by iafan** [comment] 2018-10-31 21:54
Ok, I see where the problem is. One test uses `gzip` tool, which is not available on Windows (though you might want to install it from e.g. http://gnuwin32.sourceforge.net/packages/gzip.htm and available in the %PATH% just to make the test pass). I'll need to think of using something else instead of `gzip` to make it Windows-friendly, since it is provided there in the test just as an example.

Anyways, this error is pretty harmless, so you can safely use the latest version of Serge which you already have, just make sure the path to the `/bin` subfolder is also added to your %PATH% so that you can invoke `serge` from anywhere.

**Comment by dragosv** [comment] 2018-11-01 18:13
@icnocop you can also try to use the fork of serge that has all the translation plugins https://github.com/dragosv/serge (including zanata)

**Comment by dragosv** [comment] 2020-03-30 15:07
This is an issue with Serge, not Serge-Plugings, so closing the issue.

**Closed as completed by dragosv** 2020-03-30 15:07 UTC
